### ISSUE TITLE
[PD] <Reflect on your your Plan to Live as a Developer>

### ISSUE THREAD

**Issue by ghost** [CodeYourFuture/Induction#8]

**Comment by maz786** [comment]
Kamino cloned this issue to [maz786/Coursework-Planner](https://github.com/maz786/Coursework-Planner/issues/25)

**Comment by maz786** [comment]
Kamino cloned this issue to [maz786/Coursework-Planner](https://github.com/maz786/Coursework-Planner/issues/31)

**Comment by maz786** [comment]
Kamino cloned this issue to [maz786/Coursework-Planner](https://github.com/maz786/Coursework-Planner/issues/64)

**Comment by maz786** [comment]
Kamino cloned this issue to [maz786/Coursework-Planner](https://github.com/maz786/Coursework-Planner/issues/78)

**Comment by Ayman-matoo** [comment]
Kamino cloned this issue to [Ayman-matoo/Coursework-Planner](https://github.com/Ayman-matoo/Coursework-Planner/issues/22)

**Comment by kfklein15** [comment]
This has been created incorrectly. Please do not clone.
